spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:vehicle_db}
    username: ${POSTGRES_USER:carrental}
    password: ${POSTGRES_PASSWORD:carrental}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
