-- customer-service: only the customers table (per-service database)
CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(30) NOT NULL,
    license_number VARCHAR(50) NOT NULL,
    license_expiry_date DATE NOT NULL,
    eligible_to_rent BOOLEAN NOT NULL
);

INSERT INTO customers (full_name, email, phone, license_number, license_expiry_date, eligible_to_rent) VALUES
    ('John Smith', 'john@example.com', '5141111111', 'LIC12345', DATE '2028-12-31', TRUE),
    ('Sara Lee', 'sara@example.com', '5142222222', 'LIC67890', DATE '2027-06-30', TRUE),
    ('Mike Brown', 'mike@example.com', '5143333333', 'LIC99999', DATE '2026-08-15', TRUE),
    ('Emma Wilson', 'emma@example.com', '5144444444', 'LIC77777', DATE '2029-01-01', TRUE),
    ('David Clark', 'david@example.com', '5145555555', 'LIC88888', DATE '2025-12-20', FALSE);
